// Website prompts — Home Exterior Services B (generated from the dental master template)
export const HOME_EXTERIOR_B_PROMPTS: Record<string, string> = {
  "Cleaning Company": [
    "Build a complete multi-page website for the residential cleaning company described in BUSINESS DETAILS at the end of this prompt. Use those details everywhere; never invent facts. If a detail is missing, still build the full site with clearly marked placeholders such as \"[COMPANY NAME]\", \"[4.8 stars - 200+ reviews]\", \"[$XXX-$XXX per visit]\", \"[OWNER NAME]\". Never fabricate a real-looking number, name, or review.",
    "",
    "Premium and custom-feeling, never a template: generous white space and subtle animation - a gentle fade-up per section on first scroll, hover lift on cards and buttons, count-up stats, smooth page and quiz-step transitions, never busy. The feeling is: a sunlit, freshly cleaned home and a company you would happily hand your keys to.",
    "",
    "BRAND",
    "Colors: eucalyptus green (#2E8B6F) primary, bright white (#FCFCFA) backgrounds, soft sage (#DFEDE6) accents, charcoal (#27303A) text (swap in brand colors from BUSINESS DETAILS if provided). Typography: friendly rounded sans headlines, clean neutral sans body. Imagery: bright natural-light photos of real tidy homes and real-looking cleaners - never rubber-glove-and-spray-bottle close-ups, feather dusters, or posed maids in aprons; generate images in this style. Tone: warm plain English, judgment-free, for a busy person slightly embarrassed about their home who just wants it handled.",
    "",
    "BUILD 6 PAGES:",
    "",
    "PAGE 1 - HOME",
    "Hero: bright full-width photo, outcome-focused headline (write 3 options), primary button \"Get My Free Quote\", secondary link \"Take the 60-Second Clean Home Quiz\". Count-up trust bar: rating and reviews, years, homes cleaned, recurring families. \"How we're different\": 3 differentiator cards. Services preview: 4 cards (Recurring Cleaning Plans, Deep Cleaning, Move-In / Move-Out, Add-Ons & Specialty), one sentence each, recurring first. Gradient green band: \"Not sure what your home needs?\" linking to the quiz. Proof: 3 before-and-after rooms with a draggable divider (mouse and touch, \"slide to compare\" hint, captions like \"Kitchen - first deep clean\", tap-crossfade fallback). Carousel of the 3 reviews. Strip: flat rates, no contracts, the guarantee from BUSINESS DETAILS. Meet-the-owner teaser. Booking section: embedded calendar with address, hours, phone, map.",
    "",
    "PAGE 2 - SERVICES",
    "Four anchored sections (the groups above), sticky in-page nav. Each: a question heading like \"What's included in a recurring clean?\", the direct 2-3 sentence answer FIRST, details, the honest price range from BUSINESS DETAILS, a 3-question FAQ, a booking button. Before-and-after sliders in Deep Cleaning and Move-In / Move-Out only.",
    "",
    "PAGE 3 - CLEAN HOME QUIZ (the most important page)",
    "A full-screen quiz named \"The 60-Second Clean Home Quiz\": one question per step, big tappable cards, auto-advance, progress bar, back navigation.",
    "1. What does your home need most? (Regular upkeep / A serious deep clean / A move-in or move-out clean / A reset after an event or renovation / Not sure yet)",
    "2. How big is your home? (1-2 bedrooms / 3 bedrooms / 4+ bedrooms)",
    "3. How often? (Weekly / Every two weeks / Monthly / Just once)",
    "4. Any pets? (Dogs / Cats / Both / No pets)",
    "5. What one area would you love to never worry about again? (open text)",
    "6. How soon do you want to get started? (ASAP / This month / Just researching)",
    "Capture BEFORE results - \"Almost done - where should we send your personalized cleaning plan?\" - name, email, phone. Then a warm 3-4 sentence result per question-1 answer (write all 5), each ending with the embedded booking calendar. Tag every quiz lead \"quiz-lead\".",
    "",
    "PAGE 4 - PRICING (the lead magnet)",
    "Headline: \"Honest answers about cleaning cost - before anyone steps inside your door.\" Multi-step estimate tool: service (recurring / deep clean / move-in or move-out / not sure), home size (1-2 / 3 / 4+ bedrooms), timing, capture (name, email), then the honest range from BUSINESS DETAILS, a note that the exact price is confirmed at a free walkthrough, a \"Book a Free Walkthrough\" button, and one reassuring line that it usually costs less than people assume and the price is locked before work starts. Below: flat-rate pricing explained (no contracts, pause anytime), what every clean includes, a 4-question FAQ. Tag these leads \"quote-lead\".",
    "",
    "PAGE 5 - ABOUT",
    "The owner's story in warm first person from BUSINESS DETAILS (2-3 short paragraphs), team with names and roles, \"Our promises\" with 3 items (same team every visit / free re-clean if anything was missed / keys and codes locked down - adjust to the real promises), and only the credentials listed.",
    "",
    "PAGE 6 - CONTACT / BOOK",
    "The booking calendar as the hero, click-to-call phone, address with embedded map, hours, a service-area note, and a short message form.",
    "",
    "GLOBAL REQUIREMENTS",
    "Sticky header: logo, links, phone, a green \"Book Now\" button always visible, even in the mobile menu. Floating mobile \"Book\" button that never covers content. Footer: business NAP EXACTLY as in BUSINESS DETAILS, hours, quick links, Google reviews link, privacy policy. All forms and the quiz create tagged CRM contacts. Mobile-first, thumb-sized buttons, one-handed quiz. Accessibility: contrast, alt text, focus states. SEO: unique titles and metas naming the city, LocalBusiness schema with the exact NAP and hours, FAQ schema on FAQs. Rewrite anything generic to any cleaning site into something specific to this company; flag claims you cannot make specific.",
    "",
    "=====================================================",
    "BUSINESS DETAILS",
    "(Pre-filled with fictional demo data so the prompt works",
    "as-is for demos and portfolio builds. For a real client,",
    "replace every line below with their real information -",
    "whatever you leave unchanged will appear on the site.)",
    "=====================================================",
    "",
    "Company name: Fresh Nest Cleaning Co.",
    "Type: recurring residential cleaning, plus deep cleans and move-outs",
    "City: Willow Park area, Riverton",
    "Exact footer NAP (must match Google Business Profile): Fresh Nest Cleaning Co., 41 Birchwood Lane, Riverton, (555) 320-4471",
    "Hours: Mon-Fri 8am-5pm, Sat 9am-1pm, closed Sunday",
    "Service area: Riverton and suburbs within 20 miles",
    "Owner: Elena Ruiz",
    "About-story facts: started solo 11 years ago, ran hotel housekeeping before that, saw what a clean home did for her own stress as a working mom",
    "Team: Marisol (lead cleaner, 8 years), Dana (team lead), Petra (scheduling)",
    "Credentials: bonded and insured, background-checked cleaners",
    "Google: 4.9 stars, 187 reviews",
    "Years serving the city: 11",
    "Homes cleaned: 9,000+ cleans",
    "3 differentiators: same team every visit, 24-hour re-clean guarantee, flat rates with no contracts",
    "3 reviews (first names): \"Same two cleaners every week for three years.\" - Karen / \"Full deposit back after their move-out clean.\" - Jordan / \"I got my Saturdays back.\" - Alicia",
    "Pricing style: flat rates, no contracts, pause anytime, free 24-hour re-clean",
    "Price ranges (published):",
    "- Recurring clean (per visit): $130-$190",
    "- First-time clean: $180-$260",
    "- Deep clean: $280-$450",
    "- Move-in / move-out clean: $320-$520",
    "- Inside fridge or oven add-on: $35-$55 each",
    "Booking calendar: Free In-Home Walkthrough",
    "Pipeline for quiz/quote leads: New Leads, stage \"Quiz/Quote Lead\"",
    "Brand colors: use the green palette above",
    "Logo available?: no - create a simple wordmark",
  ].join("\n"),

  "Sign Company": [
    "Build a complete multi-page website for the commercial sign company described in BUSINESS DETAILS at the end of this prompt. Use those details everywhere; never invent facts. If a detail is missing, still build the full site with clearly marked placeholders such as \"[COMPANY NAME]\", \"[350+ signs installed]\", \"[$X,XXX-$X,XXX]\", \"[OWNER NAME]\". Never fabricate a real-looking number, name, or review.",
    "",
    "Premium and custom-feeling, never a template: bold, precise, generous white space and subtle animation - a gentle fade-up per section on first scroll, hover lift on cards and buttons, count-up stats, smooth page and quiz-step transitions, never busy. The feeling is: a serious fabrication shop that makes businesses impossible to miss - and hits its install dates.",
    "",
    "BRAND",
    "Colors: deep navy (#1B2A4A) primary, signal orange (#F26A21) accents, light steel gray (#F4F5F7) backgrounds, ink (#20242B) text (swap in brand colors from BUSINESS DETAILS if provided). Typography: strong condensed industrial sans headlines, neutral grotesque body. Imagery: real installed signage at dusk and daylight, bucket-truck installs, shop fabrication shots - never generic neon OPEN signs, clip-art billboards, or stock handshakes; generate images in this style. Tone: direct plain English for an owner or facilities manager who needs a sign designed, permitted, and installed on time - and has been burned by a slow shop before.",
    "",
    "BUILD 6 PAGES:",
    "",
    "PAGE 1 - HOME",
    "Hero: full-width landmark-install photo, outcome-focused headline (write 3 options), primary button \"Request a Quote\", secondary link \"Take the 60-Second Sign Finder\". Count-up trust bar: signs installed, years, cities served, on-time install rate. \"How we're different\": 3 differentiator cards. Services preview: 4 cards (Sign Design & Branding, Fabrication, Installation & Permitting, Repair & Maintenance), one sentence each. Gradient navy band: \"Not sure what sign your business needs?\" linking to the quiz. Proof: a filterable portfolio gallery (channel letters, monument, interior, vehicle) of 6-9 tiles with hover captions naming sign type and business category - no invented client names - plus a compact numbers wall. Carousel of the 3 reviews. Leasing strip: sign leasing from the monthly amount listed. Meet-the-owner teaser. Booking section: embedded consultation calendar with address, hours, phone, map.",
    "",
    "PAGE 2 - SERVICES",
    "Four anchored sections (the groups above), sticky in-page nav. Each: a question heading like \"How long does a channel letter sign take?\", the direct 2-3 sentence answer FIRST, details, the honest price range from BUSINESS DETAILS, a 3-question FAQ, a quote button. A small shop-and-finished-work gallery strip in Fabrication only.",
    "",
    "PAGE 3 - SIGN FINDER QUIZ (the most important page)",
    "A full-screen quiz named \"The 60-Second Sign Finder\": one question per step, big tappable cards, auto-advance, progress bar, back navigation.",
    "1. What kind of sign do you need? (Storefront or building sign / Monument or pylon / Interior or lobby signage / Vehicle graphics or wraps / Not sure yet)",
    "2. New location or replacing an existing sign? (Brand-new location / Replacing or updating / Adding to what we have)",
    "3. Do you have artwork ready? (Print-ready files / A logo but nothing sign-ready / Starting from scratch)",
    "4. Own the building or lease? (Own / Lease - landlord approval needed / Not sure)",
    "5. Describe the sign you're picturing or the problem you're solving. (open text)",
    "6. How soon do you want to get started? (ASAP / This month / Just researching)",
    "Capture BEFORE results - \"Almost done - where should we send your personalized sign plan?\" - name, email, phone. Then a confident 3-4 sentence result per question-1 answer (write all 5), each ending with the embedded consultation calendar. Tag every quiz lead \"quiz-lead\".",
    "",
    "PAGE 4 - PRICING (the lead magnet)",
    "Headline: \"Honest sign pricing - before you sit through a single sales call.\" Multi-step estimate tool: sign type (channel letters / monument / cabinet / interior / vehicle / not sure), illuminated or non-illuminated, timing, capture (name, email), then the honest range from BUSINESS DETAILS, a note that exact quotes need a site survey, a \"Book a Site Survey\" button, and a reassuring line that every number becomes a written fixed quote before fabrication. Below: leasing explained, what every quote includes (survey, permits, engineering, install), a 4-question FAQ. Tag these leads \"quote-lead\".",
    "",
    "PAGE 5 - ABOUT",
    "The owner's story in plain first person from BUSINESS DETAILS (2-3 short paragraphs), team with names and roles, \"Our promises\" with 3 items (permits handled in-house / a rendering approved before fabrication / install dates honored - adjust to the real promises), shop photos, and only the licenses listed.",
    "",
    "PAGE 6 - CONTACT / BOOK",
    "The consultation calendar as the hero, click-to-call phone, address with embedded map, hours, a service-area note, and a short project-inquiry form.",
    "",
    "GLOBAL REQUIREMENTS",
    "Sticky header: logo, links, phone, an orange \"Request a Quote\" button always visible, even in the mobile menu. Floating mobile \"Quote\" button that never covers content. Footer: business NAP EXACTLY as in BUSINESS DETAILS, hours, quick links, Google reviews link, privacy policy. All forms and the quiz create tagged CRM contacts. Mobile-first, thumb-sized buttons, one-handed quiz. Accessibility: contrast, alt text, focus states. SEO: unique titles and metas naming the city, LocalBusiness schema with the exact NAP and hours, FAQ schema on FAQs. Rewrite anything generic to any sign shop's site into something specific to this company; flag claims you cannot make specific.",
    "",
    "=====================================================",
    "BUSINESS DETAILS",
    "(Pre-filled with fictional demo data so the prompt works",
    "as-is for demos and portfolio builds. For a real client,",
    "replace every line below with their real information -",
    "whatever you leave unchanged will appear on the site.)",
    "=====================================================",
    "",
    "Company name: Summit Sign Works",
    "Type: full service - design, fabrication, installation",
    "City: industrial district, Cedar Falls",
    "Exact footer NAP (must match Google Business Profile): Summit Sign Works, 1180 Foundry Road, Cedar Falls, (555) 487-2210",
    "Hours: Mon-Fri 7:30am-5pm, closed weekends",
    "Service area: Cedar Falls and a 90-mile radius; statewide rollouts",
    "Owner: Dale Kowalski",
    "About-story facts: started as a bucket-truck install helper 19 years ago, bought the shop from his retiring boss, still climbs on hard installs",
    "Team: Renee (project manager, 12 years), Otis (lead fabricator), Miguel (install crew lead)",
    "Licenses: state licensed sign contractor, UL-listed shop, certified crane operators",
    "Google: 4.8 stars, 96 reviews",
    "Years in business: 19",
    "Signs installed: 1,400+",
    "3 differentiators: permits handled entirely in-house, a rendering approved before fabrication, a written install date honored 98% of the time",
    "3 reviews (first names): \"They untangled our permit mess; sign up three weeks later.\" - Priya / \"Our monument sign shrugged off two hailstorms.\" - Glenn / \"Five storefronts, five on-time installs.\" - Tamara",
    "Leasing: for qualified businesses, from $199/month",
    "Price ranges (published):",
    "- Illuminated channel letters: $3,500-$9,000",
    "- Monument sign: $8,000-$25,000",
    "- Cabinet sign: $2,500-$6,500",
    "- Interior / lobby sign: $900-$2,800",
    "- Vehicle graphics or partial wrap: $650-$3,200",
    "- Site survey and permit package: $350-$900 (credited if you proceed)",
    "Booking calendar: Sign Consultation",
    "Pipeline for quiz/quote leads: New Leads, stage \"Quiz/Quote Lead\"",
    "Brand colors: use the navy and orange palette above",
    "Logo available?: no - create a simple bold wordmark",
  ].join("\n"),

  "Home Restoration": [
    "Build a complete multi-page website for the home restoration company described in BUSINESS DETAILS at the end of this prompt. Use those details everywhere; never invent facts. If a detail is missing, still build the full site with clearly marked placeholders such as \"[COMPANY NAME]\", \"[1,200+ homes restored]\", \"[$X,XXX-$X,XXX]\", \"[OWNER NAME]\". Never fabricate a real-looking number, name, or review.",
    "",
    "Premium and custom-feeling, never a template: calm, steady, generous white space and subtle animation - a gentle fade-up per section on first scroll, hover lift on cards and buttons, count-up stats, smooth page and quiz-step transitions, never busy. The feeling is: a steady hand on your shoulder on the worst day your house has ever had.",
    "",
    "BRAND",
    "Colors: deep steady blue (#1E4E79) primary, warm amber (#E8A33D) accents, soft light gray (#F8F9FA) backgrounds, dark slate (#232A31) text (swap in brand colors from BUSINESS DETAILS if provided). Typography: solid humanist sans headlines, highly readable body. Imagery: uniformed crews arriving, drying equipment in place, beautifully restored rooms - never burning-house drama, staged floods, or crying homeowners; the site must lower the visitor's heart rate; generate images in this style. Tone: calm plain English, short sentences, for someone standing in a wet or smoke-damaged house who is overwhelmed and needs to know exactly what happens next.",
    "",
    "BUILD 6 PAGES:",
    "",
    "PAGE 1 - HOME",
    "Hero: full-width photo of a restored living space, outcome-focused headline (write 3 options), primary click-to-call button \"Call Now - 24/7 Response\", secondary link \"Take the 60-Second Damage Check\". Count-up trust bar: rating and reviews, years, homes restored, average response minutes. \"How we're different\": 3 differentiator cards. Services preview: 4 cards (Water Damage Restoration, Fire & Smoke Restoration, Storm Damage Repair, Rebuild & Reconstruction), one sentence each. Gradient blue band: \"Not sure how bad the damage is?\" linking to the quiz. Proof: 3 before-and-after comparisons with a draggable divider (mouse and touch, \"slide to compare\" hint, captions like \"Kitchen water damage - 3 weeks\", tap-crossfade fallback). Carousel of the 3 reviews. Insurance strip: every carrier, full claim documentation, direct billing, plus the financing line from BUSINESS DETAILS. Meet-the-owner teaser. Booking section: embedded assessment calendar with address, hours, phone, map.",
    "",
    "PAGE 2 - SERVICES",
    "Four anchored sections (the groups above), sticky in-page nav. Each: a question heading like \"What should I do in the first hour after a flood?\", the direct 2-3 sentence answer FIRST, the step-by-step process, the honest price range from BUSINESS DETAILS with an insurance note, a 3-question FAQ, a booking button. Before-and-after sliders in Water Damage and Fire & Smoke only.",
    "",
    "PAGE 3 - DAMAGE CHECK QUIZ (the most important page)",
    "A full-screen quiz named \"The 60-Second Damage Check\": one question per step, big tappable cards, auto-advance, progress bar, back navigation.",
    "1. What happened to your home? (Water or flooding / Fire or smoke / Storm or wind damage / Mold discovery / Not sure what caused it)",
    "2. When did it happen? (Last 24 hours / This week / Over a week ago / Ongoing for a while)",
    "3. Is the damage still active? (Yes, ongoing / No, it's stopped / Not sure)",
    "4. Will you file an insurance claim? (Yes / No, paying directly / Not sure how that works)",
    "5. Briefly describe what you're seeing. (open text)",
    "6. How soon do you want help? (ASAP / This month / Just researching)",
    "Capture BEFORE results - \"Almost done - where should we send your personalized recovery plan?\" - name, email, phone. Then a calm 3-4 sentence result per question-1 answer (write all 5), each ending with the embedded assessment calendar; on active-damage answers repeat the 24/7 phone number above it. Tag every quiz lead \"quiz-lead\".",
    "",
    "PAGE 4 - COST & INSURANCE (the lead magnet)",
    "Headline: \"Honest answers about restoration cost - and what insurance usually covers.\" Multi-step estimate tool: damage type (water / fire and smoke / storm / mold / not sure), insurance status (filing a claim / paying directly / not sure), timing, capture (name, email), then the honest range from BUSINESS DETAILS, a note that exact scope requires a free on-site assessment, a \"Book a Free Assessment\" button, and one reassuring line that in most covered claims homeowners pay only their deductible, confirmed before work begins. Below: how claims work (we document, photograph, bill the carrier directly), financing for non-covered work, a 4-question FAQ. Tag these leads \"quote-lead\".",
    "",
    "PAGE 5 - ABOUT",
    "The owner's story in calm first person from BUSINESS DETAILS (2-3 short paragraphs), team with names and roles, \"Our promises\" with 3 items (we answer the phone at 3am / everything documented for your claim / one company from cleanup to rebuild - adjust to the real promises), crew photos, and only the certifications listed.",
    "",
    "PAGE 6 - CONTACT / BOOK",
    "The assessment calendar as the hero, click-to-call phone, address with embedded map, hours, a service-area note, an emergency banner - \"Water coming in right now? Call us - crews are on call 24/7.\" - and a short message form.",
    "",
    "GLOBAL REQUIREMENTS",
    "Sticky header: logo, page links, the 24/7 phone, a blue \"Get Help Now\" button always visible, even in the mobile menu. Floating mobile \"Call 24/7\" button that never covers content. Footer: business NAP EXACTLY as in BUSINESS DETAILS, hours, quick links, Google reviews link, privacy policy. All forms and the quiz create tagged CRM contacts. Mobile-first, thumb-sized buttons, one-handed quiz. Accessibility: contrast, alt text, focus states. SEO: unique titles and metas naming the city, LocalBusiness schema with the exact NAP and hours, FAQ schema on FAQs. Rewrite anything generic to any restoration site into something specific to this company; flag claims you cannot make specific.",
    "",
    "=====================================================",
    "BUSINESS DETAILS",
    "(Pre-filled with fictional demo data so the prompt works",
    "as-is for demos and portfolio builds. For a real client,",
    "replace every line below with their real information -",
    "whatever you leave unchanged will appear on the site.)",
    "=====================================================",
    "",
    "Company name: Solid Ground Restoration",
    "Type: full service - water, fire, storm, rebuild",
    "City: Fairview and surrounding county",
    "Exact footer NAP (must match Google Business Profile): Solid Ground Restoration, 720 Commerce Drive, Fairview, (555) 908-3345",
    "Hours: office Mon-Fri 8am-6pm; emergency crews on call 24/7",
    "Service area: within 60 miles of Fairview; average emergency response 47 minutes",
    "Owner: Marcus Hale",
    "About-story facts: nine years as a city firefighter, 16 years in restoration, started the company after helping four neighbors gut their homes following the creek flood",
    "Team: Dee (claims coordinator, 10 years), Walt (mitigation lead), Sonia (rebuild project manager)",
    "Certifications: IICRC-certified firm in water and fire restoration, state licensed general contractor",
    "Google: 4.9 stars, 214 reviews",
    "Years serving the city: 16",
    "Homes restored: 1,300+",
    "3 differentiators: 24/7 live-answered phone with a 60-minute response target, insurance claim documentation handled for you, one company from mitigation through rebuild",
    "3 reviews (first names): \"At our house at 2am, pumps running by 3.\" - Denise / \"They handled the whole claim; we paid our deductible, nothing else.\" - Roy / \"You cannot tell there was ever a fire in our kitchen.\" - Amara",
    "Insurance and financing: works with all major carriers, bills insurance directly with photo documentation; financing for non-covered work from $125/month",
    "Price ranges (published):",
    "- Emergency water extraction and drying: $1,500-$4,500",
    "- Fire and smoke cleanup: $4,000-$25,000",
    "- Storm board-up and roof tarping: $450-$1,200",
    "- Mold remediation: $1,800-$6,000",
    "- Rebuild and reconstruction: scoped per project, most from $10,000",
    "- On-site damage assessment: free",
    "Booking calendar: Free Damage Assessment",
    "Pipeline for quiz/quote leads: New Leads, stage \"Quiz/Quote Lead\"",
    "Brand colors: use the blue palette above",
    "Logo available?: no - create a simple sturdy wordmark",
  ].join("\n"),

  "Decking Contractor": [
    "Build a complete multi-page website for the deck design and build contractor described in BUSINESS DETAILS at the end of this prompt. Use those details everywhere; never invent facts. If a detail is missing, still build the full site with clearly marked placeholders such as \"[COMPANY NAME]\", \"[600+ decks built]\", \"[$XX,XXX-$XX,XXX]\", \"[OWNER NAME]\". Never fabricate a real-looking number, name, or review.",
    "",
    "Premium and custom-feeling, never a template: warm, crafted, generous white space and subtle animation - a gentle fade-up per section on first scroll, hover lift on cards and buttons, count-up stats, smooth page and quiz-step transitions, never busy. The feeling is: a summer evening on a beautifully built deck that was finished on time and on budget.",
    "",
    "BRAND",
    "Colors: deep forest green (#2F4A3A) primary, warm cedar (#C97B4A) accents, soft cream (#FAF7F2) backgrounds, dark espresso (#2B2420) text (swap in brand colors from BUSINESS DETAILS if provided). Typography: sturdy slab or serif headlines, clean warm sans body. Imagery: golden-hour photos of finished decks being lived on - dinners, kids, string lights - plus honest build-in-progress shots; never lumber-pile stock photos, catalog patio furniture, or 3D renders passed off as real; generate images in this style. Tone: warm plain English, excited but honest, for a homeowner who has dreamed about their backyard for two summers and fears contractor horror stories.",
    "",
    "BUILD 6 PAGES:",
    "",
    "PAGE 1 - HOME",
    "Hero: full-width golden-hour deck photo, outcome-focused headline (write 3 options), primary button \"Book a Free Design Consult\", secondary link \"Take the 60-Second Deck Planner\". Count-up trust bar: rating and reviews, years, decks built, on-schedule rate. \"How we're different\": 3 differentiator cards. Services preview: 4 cards (Custom Design & Build, Composite Decking, Wood Decks & Restoration, Railings, Pergolas & Features), one sentence each. Gradient green band: \"Not sure what your backyard could be?\" linking to the quiz. Proof: 3 before-and-after backyard comparisons with a draggable divider (mouse and touch, \"slide to compare\" hint, captions like \"Composite deck with pergola - 3 weeks\", tap-crossfade fallback). Carousel of the 3 reviews. Financing strip: plans from the monthly amount listed. Meet-the-owner teaser. Booking section: embedded consultation calendar with address, hours, phone, map.",
    "",
    "PAGE 2 - SERVICES",
    "Four anchored sections (the groups above), sticky in-page nav. Each: a question heading like \"How much does a composite deck really cost?\", the direct 2-3 sentence answer FIRST, materials and timeline details, the honest price range from BUSINESS DETAILS, a 3-question FAQ, a booking button. Before-and-after sliders in Custom Design & Build and Wood Decks & Restoration only.",
    "",
    "PAGE 3 - DECK PLANNER QUIZ (the most important page)",
    "A full-screen quiz named \"The 60-Second Deck Planner\": one question per step, big tappable cards, auto-advance, progress bar, back navigation.",
    "1. What are you dreaming of? (A brand-new deck / Replacing an old deck / Repairing or restoring what I have / Adding features - pergola, railing, lighting / Not sure yet)",
    "2. Which material? (Composite / Wood / Whatever lasts longest / Undecided)",
    "3. Roughly how big? (Under 200 sq ft / 200-400 sq ft / 400+ sq ft / No idea)",
    "4. How will you use it most? (Entertaining / Family dinners and kids / Quiet mornings / All of the above)",
    "5. Describe your dream backyard in one sentence. (open text)",
    "6. How soon do you want to get started? (ASAP / This month / Just researching)",
    "Capture BEFORE results - \"Almost done - where should we send your personalized deck plan?\" - name, email, phone. Then a warm 3-4 sentence result per question-1 answer (write all 5), each ending with the embedded consultation calendar. Tag every quiz lead \"quiz-lead\".",
    "",
    "PAGE 4 - COST & FINANCING (the lead magnet)",
    "Headline: \"Honest deck pricing - before you talk to a single salesperson.\" Multi-step estimate tool: project (new composite deck / new wood deck / resurface or restore / pergola or features / not sure), approximate size (under 200 / 200-400 / 400+ sq ft), timing, capture (name, email), then the honest range from BUSINESS DETAILS, a note that a fixed quote comes from a free on-site design consult, a \"Book a Free Design Consult\" button, and one reassuring line that the quote is fixed in writing before a single board is ordered. Below: financing explained, what every quote includes (design, permits, materials, labor, cleanup), a 4-question FAQ. Tag these leads \"quote-lead\".",
    "",
    "PAGE 5 - ABOUT",
    "The owner's story in warm first person from BUSINESS DETAILS (2-3 short paragraphs), team with names and roles, \"Our promises\" with 3 items (a fixed price before we start / a tidy site every night / we show up when we said - adjust to the real promises), build photos, and only the licenses listed.",
    "",
    "PAGE 6 - CONTACT / BOOK",
    "The consultation calendar as the hero, click-to-call phone, address with embedded map, hours, a service-area note, and a short message form for describing project ideas.",
    "",
    "GLOBAL REQUIREMENTS",
    "Sticky header: logo, links, phone, a cedar \"Book a Consult\" button always visible, even in the mobile menu. Floating mobile \"Book\" button that never covers content. Footer: business NAP EXACTLY as in BUSINESS DETAILS, hours, quick links, Google reviews link, privacy policy. All forms and the quiz create tagged CRM contacts. Mobile-first, thumb-sized buttons, one-handed quiz. Accessibility: contrast, alt text, focus states. SEO: unique titles and metas naming the city, LocalBusiness schema with the exact NAP and hours, FAQ schema on FAQs. Rewrite anything generic to any deck builder's site into something specific to this company; flag claims you cannot make specific.",
    "",
    "=====================================================",
    "BUSINESS DETAILS",
    "(Pre-filled with fictional demo data so the prompt works",
    "as-is for demos and portfolio builds. For a real client,",
    "replace every line below with their real information -",
    "whatever you leave unchanged will appear on the site.)",
    "=====================================================",
    "",
    "Company name: Timberline Deck Co.",
    "Type: design-build with repair and restoration",
    "City: Brookfield and the north suburbs",
    "Exact footer NAP (must match Google Business Profile): Timberline Deck Co., 96 Sawmill Court, Brookfield, (555) 641-7788",
    "Hours: Mon-Fri 7am-5pm, Sat 9am-12pm by appointment, closed Sunday",
    "Service area: Brookfield and towns within 35 miles",
    "Owner: Tom Alvarez",
    "About-story facts: a finish carpenter for 22 years, built his first deck at 15 with his dad, started the company after years of fixing decks other contractors rushed",
    "Team: Casey (design consultant), Luis (crew foreman, 9 years), Beth (office and scheduling)",
    "Licenses: state licensed and insured contractor, certified installer for two major composite brands",
    "Google: 4.9 stars, 143 reviews",
    "Years building in the city: 12",
    "Decks built: 640+",
    "3 differentiators: a fixed written price before work begins, a 3D design preview at the free consult, a 25-year workmanship warranty on framing",
    "3 reviews (first names): \"The finished deck looks exactly like the 3D picture.\" - Sandra / \"Done in 11 days; final bill matched the quote.\" - Kevin / \"They rebuilt the deck another company botched.\" - Monique",
    "Financing: through our lending partner, plans from $189/month",
    "Price ranges (published):",
    "- New composite deck: $16,000-$32,000",
    "- New wood deck: $9,000-$18,000",
    "- Deck resurfacing (new boards on solid framing): $6,000-$12,000",
    "- Railing upgrade: $3,500-$8,000",
    "- Pergola addition: $4,500-$12,000",
    "- Repairs and restoration visits: $450-$1,800",
    "Booking calendar: Free Design Consultation",
    "Pipeline for quiz/quote leads: New Leads, stage \"Quiz/Quote Lead\"",
    "Brand colors: use the green and cedar palette above",
    "Logo available?: no - create a simple crafted wordmark",
  ].join("\n"),

  "Tree Trimming": [
    "Build a complete multi-page website for the tree trimming and removal service described in BUSINESS DETAILS at the end of this prompt. Use those details everywhere; never invent facts. If a detail is missing, still build the full site with clearly marked placeholders such as \"[COMPANY NAME]\", \"[5,000+ trees serviced]\", \"[$XXX-$X,XXX]\", \"[ARBORIST NAME]\". Never fabricate a real-looking number, name, or review.",
    "",
    "Premium and custom-feeling, never a template: grounded, capable, generous white space and subtle animation - a gentle fade-up per section on first scroll, hover lift on cards and buttons, count-up stats, smooth page and quiz-step transitions, never busy. The feeling is: the crew you call when a tree is leaning over your roof - certified, insured, completely unfazed.",
    "",
    "BRAND",
    "Colors: deep forest green (#1E4D2B) primary, warm bark brown (#7A5230) accents, soft off-white (#F7F8F5) backgrounds, charcoal (#242A26) text (swap in brand colors from BUSINESS DETAILS if provided). Typography: strong confident sans headlines, clean readable body. Imagery: real crews in harnesses and helmets working residential trees, clean finished yards, healthy pruned canopies - never chainsaw glamour close-ups, lumberjack clichés, or generic forest wallpaper; generate images in this style. Tone: plain English, steady and safety-first, for a homeowner worried about a tree threatening the house who wants professionals, not a guy with a truck and a chainsaw.",
    "",
    "BUILD 6 PAGES:",
    "",
    "PAGE 1 - HOME",
    "Hero: full-width photo of a crew working a large residential tree, outcome-focused headline (write 3 options), primary button \"Get a Free Tree Assessment\", secondary link \"Take the 60-Second Tree Check\". Count-up trust bar: rating and reviews, years, trees serviced, liability coverage amount. \"How we're different\": 3 differentiator cards. Services preview: 4 cards (Tree Trimming & Pruning, Tree Removal, Stump Grinding, Storm & Emergency Work), one sentence each. Gradient green band: \"Not sure if that tree is a problem?\" linking to the quiz. Proof: 3 before-and-after comparisons with a draggable divider (mouse and touch, \"slide to compare\" hint, captions like \"Crown reduction over the roofline - 1 day\", tap-crossfade fallback). Carousel of the 3 reviews. Safety strip: licensed, insured to the amount listed, certified arborist on every estimate - credentials from BUSINESS DETAILS only. Meet-the-owner teaser. Booking section: embedded assessment calendar with address, hours, phone, map.",
    "",
    "PAGE 2 - SERVICES",
    "Four anchored sections (the groups above), sticky in-page nav. Each: a question heading like \"When should a tree come down instead of being trimmed?\", the direct 2-3 sentence answer FIRST, details including safety and cleanup, the honest price range from BUSINESS DETAILS, a 3-question FAQ, a booking button. Before-and-after sliders in Trimming & Pruning and Tree Removal only.",
    "",
    "PAGE 3 - TREE CHECK QUIZ (the most important page)",
    "A full-screen quiz named \"The 60-Second Tree Check\": one question per step, big tappable cards, auto-advance, progress bar, back navigation.",
    "1. What's going on with your trees? (Overgrown, need trimming / A dead, dying, or leaning tree / Storm damage or a hanging limb / A stump I want gone / Not sure - I'd like an expert to look)",
    "2. How close to anything important? (Over the house or garage / Near power lines / Near a fence or shed / Open yard)",
    "3. Roughly how tall? (Under 30 ft / 30-60 ft / Over 60 ft / Not sure)",
    "4. How many trees? (One / Two or three / Four or more)",
    "5. What worries you most about the tree? (open text)",
    "6. How soon do you want it handled? (ASAP / This month / Just researching)",
    "Capture BEFORE results - \"Almost done - where should we send your personalized tree care plan?\" - name, email, phone. Then a steady 3-4 sentence result per question-1 answer (write all 5), each ending with the embedded assessment calendar; on the storm-damage path show the emergency phone number above it. Tag every quiz lead \"quiz-lead\".",
    "",
    "PAGE 4 - PRICING (the lead magnet)",
    "Headline: \"Honest tree work pricing - before anyone climbs a ladder.\" Multi-step estimate tool: service (trimming / removal / stump grinding / storm cleanup / not sure), tree height (under 30 ft / 30-60 ft / over 60 ft / not sure), timing, capture (name, email), then the honest range from BUSINESS DETAILS, a note that exact quotes need a quick free on-site look, a \"Book a Free Assessment\" button, and one reassuring line that routine trimming costs a fraction of an emergency removal, with the price confirmed on site first. Below: what drives price (height, access, proximity to structures), what's included (cleanup and haul-away, proof of insurance on request), a 4-question FAQ. Tag these leads \"quote-lead\".",
    "",
    "PAGE 5 - ABOUT",
    "The owner's story in plain first person from BUSINESS DETAILS (2-3 short paragraphs), team with names and roles, \"Our promises\" with 3 items (a certified arborist on every job / a spotless yard when we leave / proof of insurance before you ask - adjust to the real promises), crew photos, and only the certifications listed.",
    "",
    "PAGE 6 - CONTACT / BOOK",
    "The assessment calendar as the hero, click-to-call phone, address with embedded map, hours, a service-area note, an emergency banner - \"Tree down or a limb hanging after a storm? Call now - storm crews prioritize dangerous situations.\" - and a short message form.",
    "",
    "GLOBAL REQUIREMENTS",
    "Sticky header: logo, links, phone, a green \"Free Assessment\" button always visible, even in the mobile menu. Floating mobile \"Book\" button that never covers content. Footer: business NAP EXACTLY as in BUSINESS DETAILS, hours, quick links, Google reviews link, privacy policy. All forms and the quiz create tagged CRM contacts. Mobile-first, thumb-sized buttons, one-handed quiz. Accessibility: contrast, alt text, focus states. SEO: unique titles and metas naming the city, LocalBusiness schema with the exact NAP and hours, FAQ schema on FAQs. Rewrite anything generic to any tree service's site into something specific to this company; flag claims you cannot make specific.",
    "",
    "=====================================================",
    "BUSINESS DETAILS",
    "(Pre-filled with fictional demo data so the prompt works",
    "as-is for demos and portfolio builds. For a real client,",
    "replace every line below with their real information -",
    "whatever you leave unchanged will appear on the site.)",
    "=====================================================",
    "",
    "Company name: TrueNorth Tree Service",
    "Type: full service - trimming, removal, stumps, storm response",
    "City: Lakeside and the east shore towns",
    "Exact footer NAP (must match Google Business Profile): TrueNorth Tree Service, 512 Quarry Road, Lakeside, (555) 772-9034",
    "Hours: Mon-Sat 7am-6pm; storm emergency line answered 24/7",
    "Service area: Lakeside and a 40-mile radius",
    "Owner: Ray Donnelly",
    "About-story facts: an ISA Certified Arborist climbing for 18 years, started the company after a storm dropped a neighbor's oak through his own garage roof, still walks every removal over 60 feet",
    "Team: Cole (crew lead and climber, 7 years), Britt (ground operations), Manny (stump and equipment)",
    "Certifications and coverage: ISA Certified Arborist on staff, state licensed, $2 million liability insurance, workers' comp on every crew member",
    "Google: 4.9 stars, 168 reviews",
    "Years serving the city: 14",
    "Trees trimmed and removed: 5,200+",
    "3 differentiators: a certified arborist on every estimate, proof of insurance sent before scheduling, complete cleanup with haul-away in every quote",
    "3 reviews (first names): \"A 70-foot pine over our roof, gone in a day, lawn untouched.\" - Greg / \"Out at 6am after the windstorm to clear our line.\" - Nadia / \"The only company that sent an actual arborist.\" - Phil",
    "Payment note: free estimates; card, check, cash; senior discount on trimming",
    "Price ranges (published):",
    "- Tree trimming and pruning (per tree): $250-$700",
    "- Small tree removal (under 30 ft): $400-$900",
    "- Large tree removal (over 60 ft): $1,200-$3,500",
    "- Stump grinding: $120-$350 per stump",
    "- Storm and emergency work: from $600, quoted on scene",
    "Booking calendar: Free Tree Assessment",
    "Pipeline for quiz/quote leads: New Leads, stage \"Quiz/Quote Lead\"",
    "Brand colors: use the green palette above",
    "Logo available?: no - create a simple strong wordmark",
  ].join("\n"),

  "Home Remediation": [
    "Build a complete multi-page website for the home remediation company described in BUSINESS DETAILS at the end of this prompt. Use those details everywhere; never invent facts. If a detail is missing, still build the full site with clearly marked placeholders such as \"[COMPANY NAME]\", \"[900+ homes cleared]\", \"[$X,XXX-$X,XXX]\", \"[CERTIFICATION NAME]\". Never fabricate a real-looking number, name, or review.",
    "",
    "Premium and custom-feeling, never a template: clean, clinical-but-warm, generous white space and subtle animation - a gentle fade-up per section on first scroll, hover lift on cards and buttons, count-up stats, smooth page and quiz-step transitions, never busy. The feeling is: a science-first team that takes your family's air seriously - without ever using fear to sell.",
    "",
    "BRAND",
    "Colors: calm deep teal-slate (#266B6E) primary, fresh mint (#E3F0EC) accents, clean white (#FBFCFC) backgrounds, graphite (#262D33) text (swap in brand colors from BUSINESS DETAILS if provided). Typography: clean humanist sans headlines, highly readable body. Imagery: technicians with real testing equipment, tidy containment setups, bright healthy finished rooms - never hazmat-suit scare heroes, black-mold horror close-ups, or biohazard clip art; inform, never frighten; generate images in this style. Tone: calm, factual plain English, for a worried parent or homeowner who found something concerning and wants straight answers backed by testing, not scare tactics.",
    "",
    "BUILD 6 PAGES:",
    "",
    "PAGE 1 - HOME",
    "Hero: full-width photo of a bright healthy interior, outcome-focused headline (write 3 options), primary button \"Book a Home Assessment\", secondary link \"Take the 60-Second Home Health Check\". Count-up trust bar: rating and reviews, years, homes tested and cleared, clearance-test pass rate. \"How we're different\": 3 differentiator cards - lead with test-first: we test before we treat and verify with independent clearance testing after. Services preview: 4 cards (Mold Remediation, Asbestos Testing & Abatement, Air Quality & VOC Testing, Moisture Control & Prevention), one sentence each. Gradient teal band: \"Not sure what that smell or spot actually is?\" linking to the quiz. Proof: instead of before-and-after photos, a 4-step process strip (Test - Contain - Remediate - Verify) with a photo and one line each, then a numbers wall (homes cleared, pass rate, years, certifications). Carousel of the 3 reviews. Payment strip: the payment plan from BUSINESS DETAILS in one calm sentence. Meet-the-owner teaser. Booking section: embedded assessment calendar with address, hours, phone, map.",
    "",
    "PAGE 2 - SERVICES",
    "Four anchored sections (the groups above), sticky in-page nav. Each: a question heading like \"Do I really need professional mold removal?\", the direct honest 2-3 sentence answer FIRST - including when they do NOT need us; that honesty builds trust - then the test-contain-remediate-verify process, the honest price range from BUSINESS DETAILS, a 3-question FAQ, a booking button. Process photos and diagrams only, never shock imagery.",
    "",
    "PAGE 3 - HOME HEALTH CHECK QUIZ (the most important page)",
    "A full-screen quiz named \"The 60-Second Home Health Check\": one question per step, big tappable cards, auto-advance, progress bar, back navigation.",
    "1. What are you concerned about? (Visible mold / A musty smell or unexplained allergies / Asbestos before a renovation / A recent leak or flooding / Not sure - I just want testing)",
    "2. Where in the home? (Basement or crawlspace / Bathroom or kitchen / Attic / Living areas or bedrooms / Whole home)",
    "3. Is anyone in the home sensitive? (Young kids / Allergies or asthma / Older adults / No one in particular)",
    "4. Any testing done before? (Yes, recently / Yes, a while ago / Never)",
    "5. Describe what you've seen, smelled, or noticed. (open text)",
    "6. How soon do you want answers? (ASAP / This month / Just researching)",
    "Capture BEFORE results - \"Almost done - where should we send your personalized home health plan?\" - name, email, phone. Then a calm, factual 3-4 sentence result per question-1 answer (write all 5, always leading with testing, never a scare), each ending with the embedded assessment calendar. Tag every quiz lead \"quiz-lead\".",
    "",
    "PAGE 4 - COST & TESTING (the lead magnet)",
    "Headline: \"Honest remediation pricing - before anyone quotes you out of fear.\" Multi-step estimate tool: concern (mold / asbestos / air quality testing / moisture control / not sure), affected area (single room or smaller / multiple rooms / whole home or unsure), timing, capture (name, email), then the honest range from BUSINESS DETAILS, a note that exact scope always starts with testing, a \"Book a Home Assessment\" button, and one reassuring line that testing often shows the problem is smaller than feared - and if no remediation is needed, we say so in writing. Below: why testing comes first, the payment plan, what an assessment includes, a 4-question FAQ. Tag these leads \"quote-lead\".",
    "",
    "PAGE 5 - ABOUT",
    "The owner's story in calm first person from BUSINESS DETAILS (2-3 short paragraphs), team with names and roles, \"Our promises\" with 3 items (we test before we treat / we tell you when you don't need us / independent clearance testing verifies every job - adjust to the real promises), and only the certifications listed, each with a one-line plain-English explanation.",
    "",
    "PAGE 6 - CONTACT / BOOK",
    "The assessment calendar as the hero, click-to-call phone, address with embedded map, hours, a service-area note, a measured urgent line - \"Active leak or sewage backup? Call today - fast drying keeps a small problem small.\" - and a short message form.",
    "",
    "GLOBAL REQUIREMENTS",
    "Sticky header: logo, links, phone, a teal \"Book Assessment\" button always visible, even in the mobile menu. Floating mobile \"Book\" button that never covers content. Footer: business NAP EXACTLY as in BUSINESS DETAILS, hours, quick links, Google reviews link, privacy policy. All forms and the quiz create tagged CRM contacts. Mobile-first, thumb-sized buttons, one-handed quiz. Accessibility: contrast, alt text, focus states. SEO: unique titles and metas naming the city, LocalBusiness schema with the exact NAP and hours, FAQ schema on FAQs. Rewrite anything generic to any remediation site into something specific to this company; flag claims you cannot make specific.",
    "",
    "=====================================================",
    "BUSINESS DETAILS",
    "(Pre-filled with fictional demo data so the prompt works",
    "as-is for demos and portfolio builds. For a real client,",
    "replace every line below with their real information -",
    "whatever you leave unchanged will appear on the site.)",
    "=====================================================",
    "",
    "Company name: ClearPath Home Remediation",
    "Type: full environmental - mold, asbestos, air quality, moisture",
    "City: Millbrook and the river valley",
    "Exact footer NAP (must match Google Business Profile): ClearPath Home Remediation, 233 Harbor Street, Millbrook, (555) 156-8802",
    "Hours: Mon-Fri 8am-6pm, Sat 9am-2pm, closed Sunday",
    "Service area: Millbrook and communities within 50 miles",
    "Owner: Sam Whitfield",
    "About-story facts: eight years in industrial hygiene before going residential, 13 years running the company, started it after tracing his son's asthma to hidden mold behind a finished basement wall",
    "Team: Ingrid (lead technician, 9 years), Duane (abatement supervisor), Faye (assessments and client care)",
    "Certifications and licenses: IICRC-certified in mold remediation, state licensed asbestos abatement contractor, council-certified indoor environmentalist on staff",
    "Google: 4.9 stars, 121 reviews",
    "Years serving the city: 13",
    "Homes tested and cleared: 950+",
    "3 differentiators: testing before any treatment is quoted, independent third-party clearance testing after every job, a written all-clear when remediation isn't needed",
    "3 reviews (first names): \"Two companies quoted thousands; ClearPath tested and said we just needed a bathroom fan.\" - Erin / \"Containment so clean my toddler's routine never changed.\" - Marcus / \"Found the asbestos before our renovation, handled in four days.\" - Lydia",
    "Payment plans: for larger projects, from $150/month",
    "Price ranges (published):",
    "- Mold inspection with air sampling: $250-$450",
    "- Small-area mold remediation (single room): $900-$2,400",
    "- Larger mold remediation: $2,500-$7,500",
    "- Asbestos testing and survey: $300-$600",
    "- Asbestos abatement: $1,500-$8,000",
    "- Independent clearance testing: $250-$400",
    "Booking calendar: Home Assessment Visit",
    "Pipeline for quiz/quote leads: New Leads, stage \"Quiz/Quote Lead\"",
    "Brand colors: use the teal palette above",
    "Logo available?: no - create a simple clean wordmark",
  ].join("\n"),
};
